name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches: []
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      MAX_LINE_LENGTH: 120

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==21.12b0 click==7.1.2 flake8 isort

      - name: Checkout to PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      - name: Check diff files and lint
        run: |
          DIFF_FILES=$(git diff --name-only --diff-filter=d ${{ github.base_ref}} HEAD | (grep '\.py$' || true))
          if [ -z "$DIFF_FILES" ]; then
          echo "No files to lint"
          exit 0
          fi
          echo "Running flake8 lint check for only changed files"
          for FILE in $DIFF_FILES; do
            flake8 $FILE || (echo "flake8 found issues in $FILE" && exit 1)
          done

          echo "Running black format check for all files"
          black . --check \
          --line-length=${MAX_LINE_LENGTH}  \
          --force-exclude="(migrations|deploy)" || (echo "black found issues." && exit 1)

          echo "Running isort format check for all files"
          isort . --check --profile="black" \
          --extend-skip="migrations" \
          --extend-skip="deploy" || (echo "isort found issues." && exit 1)
